# Generated by Django 3.2.7 on 2021-09-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0002_auto_20210925_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.IntegerField(unique=True, verbose_name='Телефон'),
        ),
    ]
