# Generated by Django 3.2.7 on 2021-09-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0004_alter_worker_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
