# Generated by Django 3.2.7 on 2021-09-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0005_worker_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='last_login',
        ),
    ]
